### ISSUE TITLE
Can't run Mentalist

### ISSUE THREAD

**Issue by Hamidw** [sc0tfree/mentalist#20]
Hello, i made everything listed on the wiki to install Mentalist, but i get this error
here's a pastebin 
https://pastebin.com/BJ5t9SZW

System : Kali Linux 64-Bit (fresh install) French
AMD FX-6300
GT 1030
8GB DDR3

**Comment by snehashis365** [comment]
Same here

**Comment by Probsnotapro** [comment]
use
`sudo dpkg-reconfigure locales`
reconfigure all then choose the type you want to reconfigure too e.g (en_GB.UTF-8) however this will be different depending on your language but you need to remember this.
now execute
`sudo nano /usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/view/main.py`
on line 14 change `locale.setlocale(locale.LC_ALL, 'en-US')` 
to whatever your locale is named so for me would be to en_GB instead of en_US
on line 15 change `locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')`
to once again your locale is named so for me en_GB.UTF-8 instead of en_US.UTF-8
This worked for me kind of long winded im sure there is a better way but it works.

**Comment by mrrobot-clone** [comment]
not able to understand

**Comment by Matt-Cocklin** [comment]
> use
> `sudo dpkg-reconfigure locales`
> reconfigure all then choose the type you want to reconfigure too e.g (en_GB.UTF-8) however this will be different depending on your language but you need to remember this.
> now execute
> `sudo nano /usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/view/main.py`
> on line 14 change `locale.setlocale(locale.LC_ALL, 'en-US')`
> to whatever your locale is named so for me would be to en_GB instead of en_US
> on line 15 change `locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')`
> to once again your locale is named so for me en_GB.UTF-8 instead of en_US.UTF-8
> This worked for me kind of long winded im sure there is a better way but it works.

This fix worked for me, thanks!
